// Generated by CoffeeScript 1.3.1
(function() {
  var child, exec, util;

  util = require('util');

  exec = require('child_process').exec;

  child = exec('ps ax | grep stackmob', function(error, stdout, stderr) {
    var line, lines, parts, pid, _i, _len, _results;
    lines = stdout.split("\n");
    _results = [];
    for (_i = 0, _len = lines.length; _i < _len; _i++) {
      line = lines[_i];
      if (line.indexOf("stackmob server") > -1) {
        parts = line.split(" ");
        if (parts[0] === " ") {
          pid = parts[1];
        } else {
          pid = parts[0];
        }
        console.log("killing", pid);
        process.kill(pid, 'SIGKILL');
        break;
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  });

}).call(this);
